### ISSUE TITLE
update Swift Package of HLPDialog

### ISSUE THREAD

**Issue by Mahabmn** [hulop/HLPDialog#7]
good day 

I add new localization (Arabic Language) to the project , but when I add the swift package to the IOS project , the Arabic localization is not available , 

after checking the project page , I found that the swift package is not updated as master .

is there any way to update it ? 

thank you

**Comment by Mahabmn** [comment]
hello 

is there any way to update it ?

thank you

**Comment by daisukes** [comment]
Sorry for the late reply.

Assuming you are using the NavCog master branch.
It refers to the swift-package branch of HLPDialog, so we need to add the Arabic language support to the branch too.

**Comment by daisukes** [comment]
I have merged changes in master into swift-package branch.
Could you try it?

**Comment by Mahabmn** [comment]
hello , when I add it again , I didn't found the arabic .

<img width="240" alt="Screen Shot 2022-07-12 at 8 19 53 PM" src="https://user-images.githubusercontent.com/99026115/178553990-ef00eaae-d269-4e75-8bea-09d14d3b2e17.png">

**Comment by daisukes** [comment]
How did you add it?

**Comment by Mahabmn** [comment]
thorough add package in Xcode

**Comment by daisukes** [comment]
How about trying `File` -> `Packages` -> `Update to Latest Package Versions` ?

**Comment by Mahabmn** [comment]
thank you , its updated now .
